### ISSUE TITLE
Syntax highlighting conflict with othree/javascript-libraries-syntax.vim

### ISSUE THREAD

**Issue by ctaylo21** [pangloss/vim-javascript#1095]
I have an issue where enabling this plugin will cause the `othree/javascript-libraries-syntax.vim` plugin not to work (at least for syntax highlighting for chai library). Example with both plugins enabled:

<img width="353" alt="image" src="https://user-images.githubusercontent.com/1427469/34652742-1482ca70-f397-11e7-8ea4-42ec76f3eb84.png">

And now with the `vim-javascript` disabled:

<img width="351" alt="image" src="https://user-images.githubusercontent.com/1427469/34652758-4ae96c72-f397-11e7-887e-5cccb4a6e276.png">

Any ideas on how to get these two to play nice?
<hr>

*Minimal init.vim*

```
call plug#begin('~/.config/nvim/plugged')

" Syntax highlighting for javascript libraries
Plug 'othree/javascript-libraries-syntax.vim'

" Improved syntax highlighting and indentation
Plug 'pangloss/vim-javascript'

call plug#end()

" Enable syntax highlighting for JSDoc
let g:javascript_plugin_jsdoc = 1

" === javascript-libraries-syntax === "
let g:used_javascript_libs = 'underscore,requirejs,chai,jquery'
```

**Comment by texhnolyze** [comment]
it seems ```vim-javascript``` overwrites the highlighting of ```javascript-libraries-syntax.vim```. Have you tried to turn the order in which they load around (not sure if that works that way)?

**Comment by tandrewnichols** [comment]
Related: reversing the order does fix _some_ issues, but not all of them because javascript-libraries-syntax expects syntax groups named after [this convention](https://vimhelp.appspot.com/usr_44.txt.html#44.12). Meaning, they look for things like `javascriptComment` but this plugin uses the name `jsComment`. In my brief experimentation, changing the two plugins to use the same thing makes them play nicely together. Is that something you'd consider changing? (I think the author of javascript-libraries-syntax prefers to adhere to the convention, so I'm guessing they won't want to change).
