### ISSUE TITLE
Not recognize null safe operator (babel js)

### ISSUE THREAD

**Issue by phuongnd08** [pangloss/vim-javascript#1144]
```
if (data[currency]?.key) return;
```

I'm using mater version and it seems to have trouble highlighting the piece above.

**Comment by awilliams-atx** [comment]
I was having this problem at some point in the past also, so I added this to my .vimrc

```
syntax match jsOperator "??" skipwhite skipempty nextgroup=@jsExpression
```

However, I've looked through my .vimrc again, and it's gone. So...I think this should be fixed now. Can you try `git pull` from inside `~/.vim/bundle/vim-javascript`? Or otherwise update vim-javascript however you manage your plugins.

**Comment by TrySound** [comment]
It's called optional chaining operator

**Comment by amadeus** [comment]
I don't see any bugs with the optional chaining operator, works for me. However I do see an issue with the `return` statement.

Technically tho, a return statement at the top level of a file is not valid (this highlighting will work if you put that in a function), However, if we are talking accuracy, we highlight the `return` statement if you wrap the if/else in parenthesis, even at the top level of a file - which is invalid. But also technically, most bundlers wrap bundles in a function anyways... so really I should probably the return on a 1 line if statement, just because.

**Comment by amadeus** [comment]
I merged a small fix for the return statement. I see no errors with the optional chaining operator - i can re-open this issue if there are further things.
