### ISSUE TITLE
jsExpression needs an overhaul

### ISSUE THREAD

**Issue by qstrahl** [pangloss/vim-javascript#120]
`jsExpression` right now is just a `cluster` of a bunch of groups. This is wildly inaccurate, and is the source of much woe, including (but probably not limited to) issue #93.

In actuality, there are a few kinds of expressions, and they can nest. `var a = b;` is an expression. In that expression, `b` by itself is an expression; a single identifier is a valid expression, and expressions follow operators (in this case, `=`). [There are more rules](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Expressions_and_Operators).

Issue #93 -- and further issues, no doubt -- would be much easier to solve if we made `jsExpression` more robust. I kind of want to take a shot at it, but I'm pretty busy, so I probably won't get a start on it for a while. If somebody wants to tackle the issue sooner than I can get to it, feel free to reassign.

**Comment by amadeus** [comment]
This is obviously a super old issue and everything, and I doubt anyone seriously wants to take on a major rehaul of this syntax file at this juncture, however, just browsing it now, one small thing I think we can do - rid ourselves of `jsExpression` and merge it into the `jsAll` cluster. There doesn't seem to be any valid need for `jsExpression`, and in fact, it gets even worse because `jsAll` includes `jsExpression` plus a couple other things.
