### ISSUE TITLE
Folds open when typing a (

### ISSUE THREAD

**Issue by jgallen23** [pangloss/vim-javascript#206]
If I have some folds collapsed and I type a `(`, all the folds open.  It also seems to happen with `[`

**Comment by zanona** [comment]
Same here…it makes me crazy every time I need to close everything again ;)

**Comment by amadeus** [comment]
Interesting, I never came across this because I use the delimitmate plugin, which somehow seems to suppress this bug.

Not quite sure why this happens, perhaps because of unmatched `{` and `}`?

**Comment by zanona** [comment]
@amadeus It is indeed because unmatched brackets or curly braces, however, that's inevitable while writing code. I also have [LESS plugin](https://github.com/groenewege/vim-less) for vim, and it is nice that as soon as you close the curly braces finishing a declaration it folds back the previously opened folds due mismatching.

**Comment by amadeus** [comment]
@zanona any idea how they might accomplish that? A peripheral look see and I couldn't immediately detect how

**Comment by zanona** [comment]
@amadeus I am not sure how it is implemented, therefore, after testing it more thoroughly for a minute I could see that it fails sometimes and might end doing the inverse process instead. (closing when having an unmatched `}` and opening the others once that is accomplish.

It's a shame though, because this is something that is quite different from others text editors I have used in the past where they would keep the other foldings intact.

**Comment by amadeus** [comment]
Yeah, it looks like this could be a vim issue, at least with `foldmethod=syntax`.

**Comment by zanona** [comment]
Just stumbled upon this which might be really helpful: http://vim.wikia.com/wiki/Keep_folds_closed_while_inserting_text

**Comment by amadeus** [comment]
Interesting read, thanks!

However it's not something we would add to your project. Closing this issue because it's not really something should fix given it's how vim works.

**Comment by zanona** [comment]
Fair enough @amadeus thanks. In fact, I will try it out and perhaps this can also help fix #140 as well since it changes to manual when in insert mode.

**Comment by amadeus** [comment]
@zanona that's a really good point about #140, I will post there about it as well.
