### ISSUE TITLE
Html highlighting within backticks?

### ISSUE THREAD

**Issue by whitneyit** [pangloss/vim-javascript#289]
On [line 93](https://github.com/pangloss/vim-javascript/blob/master/syntax/javascript.vim#L93) there is a call to `@htmlPreproc`.

Should this enable html highlighting within `jsTemplateString`?

Currently it looks like this:

![highlight](http://i.imgur.com/XnEwnf4.png)

**Comment by goatslacker** [comment]
Enabling syntax highlighting within jsTemplateString would be a bit weird because then it would be tough to tell whether you're in a template or not. I like the current approach of leaving everything highlighted as a string except for the evaluated bits.

Something I wish we did have was syntax highlighting within the evaluated part.

**Comment by whitneyit** [comment]
Ok, Do you a way that would allow the above functionality to work from `.vimrc` file then? I tried playing around with `syntax include` but got recursion errors
