### ISSUE TITLE
'from' keyword in a multi line import statement is not highlighted 

### ISSUE THREAD

**Issue by kuc2477** [pangloss/vim-javascript#323]
For example, in the import statement like :
```
import {
  A,
  B,
  C
} from './my_module.js'
```
`from` keyword is not highlighted. es6 specification allows new lines and white spaces in an import statement so I think it would be better to support highlighting `from` keyword in multi line import statements too.

**Comment by WChargin** [comment]
Your file works for me: `from` matches `jsImportContainer → jsModuleWords` and is highlighted as `PreProc` (same as `import`).

![screenshot](https://cloud.githubusercontent.com/assets/4317806/12073239/54fab4d6-b0c9-11e5-824f-ce738d28ac7c.png)


This is because `jsImportContainer` has `contains=jsBlock`, which matches the whole `{ A, B, C }` (with appropriate newlines). So it's parsed as

    import [jsBlock:{A, B, C}] [jsModuleWords:from] [jsStringS:'./my_module.js'] ;

and `import` matches the `start` and `;` matches the `end` of `jsImportContainer`, so the region matches.
