### ISSUE TITLE
Folding is not working for me

### ISSUE THREAD

**Issue by sassanh** [pangloss/vim-javascript#328]
Thanks for this great plugin. Everything works fine here except folding, I'd be thankful if you could help me to solve this.
My vim supports folding and I see it in action for python file for example with python-mode plugin. when I run ```echo map(synstack(line("."),col(".")),'synIDattr(v:val,"name")')``` in a function block in a js file it prints out ```['jsParen', 'jsFuncBlock', 'jsParen', 'jsFuncBlock']``` which means your syntax file is loaded and is working (to be sure about that I added an echom in your syntax file and the message printed.) when I press zc on exact same position it prints out ```E490: No fold found```. Any idea what's wrong here? Let me know if I should provide more details.

P.S. ```set syntax?``` prints ```syntax=javascript```

**Comment by sassanh** [comment]
Ok, I guess you should add to the documentation that folding works if you set foldmethod to syntax.

**Comment by davidchambers** [comment]
Would you like to submit a pull request to update __README.md__, @sassanh?

**Comment by sassanh** [comment]
@davidchambers sure, will do in coming days.

**Comment by strogonoff** [comment]
To those who still can’t make folding work for them: it won’t work unless you have ``syntax on``.

Interestingly, folding in Python files with klen/python-mode has been working just fine without ``syntax``. It uses ``foldmethod=expr``, apparently.

I thought of looking into making vim-javascript folding work similarly to python-mode (I was going to use vim-javascript for the folds anyway and I don’t use ``syntax``), but for now I suppose ``foldmethod=indent`` should suffice for me after all since I try to carefully indent the code anyway.
