### ISSUE TITLE
jsAssignmentExpr not working

### ISSUE THREAD

**Issue by larsbs** [pangloss/vim-javascript#333]
```viml
syntax match   jsAssignmentExpr     /\v%([a-zA-Z_$]\k*\.)*[a-zA-Z_$]\k*\s*\=\(>\)\@!/ contains=jsFuncAssignExpr,jsAssignExpIdent,jsPrototype,jsOperator,jsThis,jsNoise,jsArgsObj
syntax match   jsAssignExpIdent     /\v[a-zA-Z_$]\k*\ze%(\s*\=)/ contained
syntax match   jsFuncAssignExpr     /\v%(%([a-zA-Z_$]\k*\.)*[a-zA-Z_$]\k*\s*\=\s*){-1,}\ze%(function\s*\*?\s*\()/ contains=jsFuncAssignObjChain,jsFuncAssignIdent,jsFunction,jsPrototype,jsOperator,jsThis,jsArgsObj contained
syntax match   jsFuncAssignObjChain /\v%([a-zA-Z_$]\k*\.)+/ contains=jsPrototype,jsNoise contained
syntax match   jsFuncAssignIdent    /\v[a-zA-Z_$]\k*\ze%(\s*\=)/ contained
```
This doesn't match anything by now and I've seen in previous pull request that this used to work. I'm using https://github.com/gerw/vim-HiLinkTrace to check it.

Look in the bottom bar that HiLinkTrace doesn't show anything when the cursor is positioned in the name of the function.

![vim-javascript](https://cloud.githubusercontent.com/assets/1436588/11914983/4af5c966-a693-11e5-86b1-ed81915b9b05.png)

**Comment by larsbs** [comment]
The offending part of the regex is at the end of `jsAssignmentExpr`. If `\(>\)\@!` is removed, everything work like a charm. What's the purpose of those bits? Not matching `Test.test = (>)`? Why are those parens escaped?

**Comment by larsbs** [comment]
This is the commit where the last part of the regex was included: https://github.com/pangloss/vim-javascript/commit/325c0487f90707ef3e3669c1125779c7e5734037

**Comment by WChargin** [comment]
The offending characters should read `%(\>)@!`, and I think just `\>@!` should work fine as well.

In normal vim regexes, `\(>\)\@!` means "match the group containing the character `>`, then perform a negative-lookahead," which ends up meaning "fail the match if the next character is `>`." In this case, the author wanted to match `x = 3` but not `x => 3`.

However, this regex has `\v` at the start, which stands for "very magic" (`:help \v`), so the groups and lookahead don't need to have a backslash, and the `>` character does.

The `%()` group, as opposed to `()`, is better because it's non-capturing, so it's faster and can be used in some places that forbid capturing (I forget whether syntax is one of these). But `@!` matches the previous atom, and `>` is a single-character atom by itself, so the group is unnecessary.

Test document:
```
let myVar = 87;
let myFunc = x => 3;
// vim: hlsearch
```
Exactly `myVar` and `myFunc` should be highlighted.

**Comment by davidchambers** [comment]
Thanks for the explanation, @WChargin!
