### ISSUE TITLE
Adding flow types to a class definition prevents proper js highlighting

### ISSUE THREAD

**Issue by gf3** [pangloss/vim-javascript#521]
When the type for the `state` property (`: State`) is added the method definition of `componentDidMount` changes from `jsClassFuncName` to `jsFuncCall`. Example snippet:

``` js
export class MyComponent extends React.Component<any, Props, State> {
  state: State = {
    value: false
  };

  componentDidMount() {
    // ...
  }
}
```

**Comment by amadeus** [comment]
So this one will be a bit more complex to fix. We are going to need to create a new specialized jsFlow group that lives only in class statements and can provide a nextgroup of `jsClassValue`. We can't do that globally to `jsFlow` since that would break things. I have some ideas, but I won't be able to iterate on them right now.

**Comment by gf3** [comment]
ahh, sounds tricky. i have another example of the highlighting going a little strange, not sure if it's related to the issue above: https://gist.github.com/gf3/25522ed3f60e389cb01c

**Comment by amadeus** [comment]
Ahh yeah, line 20, the `<R>` is throwing everything off

**Comment by amadeus** [comment]
Should be fixed in `develop`
