### ISSUE TITLE
More grief with arrow functions as class property initializers

### ISSUE THREAD

**Issue by qstrahl** [pangloss/vim-javascript#826]
Example code:
```
class Foo {
  doStuff = () => chain(this.state)
    .pick([ 'a', 'b', 'c' ])
    .merge(this.state.yep) // highlight fail!
    .omit([ 'nope' ])
    .value();
}
```

May be related to #821. In the above example, the `this` in `this.state.yep` is lacking the `jsThis` highlight group. Instead, it is matched as `jsClassBlock`. Haven't been able to figure this one out yet.

**Comment by qstrahl** [comment]
The following cases both highlight correctly:
```
// wrapping in parens...
class Foo {
  doStuff = () => (chain(this.state)
    .pick([ 'a', 'b', 'c' ])
    .merge(this.state.yep) // highlight fail!
    .omit([ 'nope' ])
    .value());
}

// wrapping in braces...
class Foo {
  doStuff = () => { chain(this.state)
    .pick([ 'a', 'b', 'c' ])
    .merge(this.state.yep) // highlight fail!
    .omit([ 'nope' ])
    .value() };
}
```

**Comment by qstrahl** [comment]
I looked into the possibility that this is a regression introduced by 432d01b2d0b2557f232d588fd0ebc95702298524 but it doesn't seem to be.

**Comment by bounceme** [comment]
I think we had a similar report a while ago, seems like this is es7 syntax. it'd be nice to have fixed though

**Comment by amadeus** [comment]
Arrow functions have always been a crazy pain in the ass to support :( Basically regexes suck for tokenizing the complexity of their different states. For example, currently, I have not found a way to support multi-line parenthesis surrounding the arguments. I.E. differentiating between arbitrary parenthesis, parenthesis that are then proceeded by an `=>` symbol, that also support potentially parenthesis inside the parenthesis because default argument params/expressions; basically it's a shit show. Most other editors I have tested don't support this. Although I did make a proposal to vim about how we could potentially fix this, but nobody ever responded to it.

Honestly, what we really need is for a JS engine to actually parse the text and apply syntax highlighting groups based on that. That would be the dream, but AFAIK there's no way Vim could do this.

Anyways, back to the current issue, let me think about this one for a bit, might have to incorporate some sort of chaining mechanism to keep the region from ending.

**Comment by bounceme** [comment]
yea, the source for facebook/flow 's parser has a few notes about arrow functions. https://github.com/facebook/flow/blob/master/src/parser/expression_parser.ml

**Comment by bounceme** [comment]
also, see https://github.com/billyvg/tigris.nvim . would something like that be stable enough for real work though?

**Comment by qstrahl** [comment]
That looks like downright black magic to me

**Comment by amadeus** [comment]
Their idea is pretty neat, but that screenshot is so misleading xD. A lot of the stuff he has 'un' highlighted, we actually do match, his colorscheme doesn't add color too it. Also there is a bug in the xml syntax file, which I tried submitting a patch for, but was never accepted.

Also,
![wtf](https://dl.dropboxusercontent.com/s/nhyrxgx54bbv1ff/all.png_50002280_2017-01-25_15-31-28.png?dl=0)

**Comment by amadeus** [comment]
@bounceme they also mention in the readme that updates are debounced by 500ms, that seems like it could feel really laggy.

This is something that would have to be built into Vim to work properly.

**Comment by billyvg** [comment]
Creator of that plugin here -- definitely not stable enough for real work, also can be bone crushingly slow with larger files. I don't think it's viable to continuously run the file through an AST parser.

**Comment by qstrahl** [comment]
I'm not sure when this was fixed - but it is fixed now
